package by.motolyha.mangaproject.controller.command;

public enum CommandType {
    SIGN_IN,
    SIGN_UP,
    LOG_OUT,
    RESET_PASSWORD,
    UPDATE_USER_PROFILE_DATA,
    CHANGE_LOCALE,

    GO_TO_READ_CHAPTER_PAGE,
    GO_TO_MANGA_INFO_PAGE,
    GO_TO_EDIT_PROFILE_PAGE,
    GO_TO_RESET_PASSWORD_PAGE,
    GO_TO_PROFILE_PAGE,
    GO_TO_SIGN_UP_PAGE,
    GO_TO_SIGN_UP_SUCCESS_PAGE,
    GO_TO_SIGN_IN_PAGE,
    GO_TO_PAGE_NOT_FOUND,
    GO_TO_HOME_PAGE;
}
